coverage:
  round: 'down'
  status:
    project: true
    patch: true
    changes: false
comment:
  layout: 'condensed_header, condensed_files, condensed_footer'
  hide_project_coverage: false
github_checks:
  annotations: true
