name: Checks
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v4
      - name: 'Set up the JDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: 'Set up the Android SDK'
        uses: android-actions/setup-android@v3
      - name: 'Run tests'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: 'Publish test report'
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
