name: Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v4

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v3

      - name: 'Set up the Android SDK'
        uses: android-actions/setup-android@v3

      - name: 'Run unit tests'
        run: ./gradlew test
  android_tests: # Based on https://github.com/ReactiveCircus/android-emulator-runner
    name: 'Android tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 21, 34 ]
        target: [ default, google_apis ]
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v4

      - name: 'Enable KVM'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v3

      - name: 'Restore AVD cache'
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.target }}

      - name: 'Create AVD and generate snapshot for cache'
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: 'Run Android tests'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          force-avd-creation: false
          script: ./gradlew connectedCheck
