name: Tests
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  unit_tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out the repository'
        uses: actions/checkout@v4

      - name: 'Set up Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v4

      - name: 'Set up the Android SDK'
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: 'Run unit tests'
        run: >-
          ./gradlew
          :model:compass:test
          :model:core:test
          :model:location:test
          :model:settings:test
          :model:sun:test
          :data:compass:testAospRelease :data:compass:testGmsRelease
          :data:location:testAospRelease :data:location:testGmsRelease
          :data:settings:testAospRelease :data:settings:testGmsRelease
          :data:sun:test
          :ui:compass:testAospRelease :ui:compass:testGmsRelease
          :ui:core:testAospRelease :ui:core:testGmsRelease
          :ui:design:testAospRelease :ui:design:testGmsRelease
          :ui:location:testAospRelease :ui:location:testGmsRelease
          :ui:settings:testAospRelease :ui:settings:testGmsRelease
          :ui:sun:testAospRelease :ui:sun:testGmsRelease
          koverXmlReport

      - name: 'Upload coverage report to Codecov'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
